sudo: false
language: python
services:
- docker
python:
- '3.5'
- '3.6'
- '3.7'
env:
- DJANGO_VERSION='>=2.0,<2.1'
- DJANGO_VERSION='>=2.1,<2.2'
- DJANGO_VERSION='>=2.2,<2.3'
before_install:
- docker run -d --rm -p 15672:15672 -p 5672:5672 -p 5671:5671 --name nameko-rabbitmq
  nameko/nameko-rabbitmq:3.6.6
install:
- pip install -q Django$DJANGO_VERSION
- pip install  python-coveralls
- pip install "virtualenv" "tox>=1.9"
- pip install -r requirements.txt
before_script:
- isort --recursive --check-only --diff dynamic_logging testproject
- flake8 dynamic_logging testproject
script:
- coverage run --source=testproject,dynamic_logging manage.py test
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    script: tox -e package
    install:
    - pip install "virtualenv" "tox>=1.9"
    before_install: []
    before_script: []
    after_success: []
    python: '3.6'
    on:
      repo: Yupeek/django-dynamic-logging
      tags: true
    if: tag IS present
    deploy:
      on:
        all_branches: true
      provider: pypi
      user: __token__
      password:
        secure: hO6ry+RLahQPAxjeWpWb2HnUieSoW245QtrxilgHPZDINXKs/yGy95M4RLsDHjMSW6fC1jPwPQ5CswYd0ZIdrMRKpkZgiOAC0vj+PbCP2fSQa9JjpCMxv16nas4xwmIZmEUtiFQ9yQh6SErlZLjTe6RQsDB6l0Q2oETzPaq/DOpXUMJfyjsvrFloC3aRzPWtLmuOiunJjzETC1ttm1zf6AlPGmSML4r28s6p+pzs0Qzob5kHC0TvcsUwBhRMM2eUwxHX2cE2piPXHTReaVPxijm/EuuPHFSCPxMZQ9/PmN56BopLRdX3hyzKSYKx0Cqz+g6A6F/iwS/8FdtLqCADETibfGQvpn63NcDBGqZHVDEdny/UtTINTEe2BW/5o6G9TlU1+VlzBXZs97P7Upk5ejHJNU+60n8B7wMhOvhrVs+x+xvKT3DSv0LORaF/p5q9PQUbHRfaW+UrCBYP0TINEsdkarxgwdbwVhNpES9s4qdqn6Obyr2ZfQdYnhycju7pVG6IXtYMVJWcTXcbgeVbi1SH2x8tymlYvn+4EIJSANPitktrBfXgiN+grw+mxPNYrDSvtTWjFhsyr8TYsgeeH65rKJojjfpXxPVcfOcFO6x6/+tldLBauougCfCddIlPxdgLBXaRI9fW1uf8m4vGffEtMBULNPyA+9UJJcEJQww=
      distributions: sdist bdist_wheel
      skip_existing: true
