# We do not use sudo
sudo: false

# Python versions for matrix
language: python
python:

  - "3.5"
  - "3.6"
  - "3.7"

# Django versions for matrix
env:

  - DJANGO_VERSION='>=2.0,<2.1'
  - DJANGO_VERSION='>=2.1,<2.2'
  - DJANGO_VERSION='>=2.2,<2.3'

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django$DJANGO_VERSION
  - pip install  python-coveralls
  - pip install "virtualenv" "tox>=1.9"
  - pip install -r requirements.txt

before_script:
  - isort --recursive --check-only --diff dynamic_logging testproject
  - flake8 dynamic_logging testproject

# Command to run tests, e.g. python setup.py test
script:
  - coverage run --source=testproject,dynamic_logging manage.py test


# Report to coveralls
after_success:
  - coveralls
